export const apartments = [
  { id: 1, name: "Apartma Center Maribor", location: "Maribor", price: 75, rating: 4.6, distance: 250 },
  { id: 2, name: "Pohorje View Apartment", location: "Maribor", price: 92, rating: 4.3, distance: 1200 },
  { id: 3, name: "Riverbank Apartment", location: "Maribor", price: 68, rating: 4.1, distance: 800 },
  { id: 4, name: "Old Town Studio", location: "Maribor", price: 55, rating: 3.9, distance: 400 },
  { id: 5, name: "Luxury Central Suite", location: "Maribor", price: 135, rating: 4.8, distance: 150 },

  { id: 6, name: "Ljubljana Old Town Studio", location: "Ljubljana", price: 110, rating: 4.7, distance: 300 },
  { id: 7, name: "Tivoli Park Apartment", location: "Ljubljana", price: 125, rating: 4.5, distance: 900 },
  { id: 8, name: "Ljubljana Riverside Loft", location: "Ljubljana", price: 149, rating: 4.9, distance: 500 },
  { id: 9, name: "Modern City Center Flat", location: "Ljubljana", price: 98, rating: 4.2, distance: 200 },
  { id: 10, name: "Dragon Bridge Apartment", location: "Ljubljana", price: 140, rating: 4.6, distance: 450 },

  { id: 11, name: "Piran Sea Breeze", location: "Piran", price: 155, rating: 4.8, distance: 100 },
  { id: 12, name: "Piran Sun&Sea Studio", location: "Piran", price: 120, rating: 4.4, distance: 300 },
  { id: 13, name: "Piran Coastal Apartment", location: "Piran", price: 175, rating: 4.7, distance: 200 },
  { id: 14, name: "Piran Lighthouse View", location: "Piran", price: 195, rating: 4.9, distance: 150 },
  { id: 15, name: "Beachfront Pearl", location: "Piran", price: 210, rating: 5.0, distance: 80 },

  { id: 16, name: "Bled Lake View Apartment", location: "Bled", price: 180, rating: 4.9, distance: 250 },
  { id: 17, name: "Bled Castle Loft", location: "Bled", price: 160, rating: 4.6, distance: 500 },
  { id: 18, name: "Bled Center Studio", location: "Bled", price: 130, rating: 4.3, distance: 300 },
  { id: 19, name: "Bled Panorama Suite", location: "Bled", price: 225, rating: 5.0, distance: 150 },
  { id: 20, name: "Bled Alpine Retreat", location: "Bled", price: 155, rating: 4.4, distance: 800 },

  { id: 21, name: "Kranjska Gora Ski Apartment", location: "Kranjska Gora", price: 140, rating: 4.5, distance: 600 },
  { id: 22, name: "Alpine Village Lodge", location: "Kranjska Gora", price: 135, rating: 4.3, distance: 1200 },
  { id: 23, name: "KG Mountain Studio", location: "Kranjska Gora", price: 110, rating: 4.1, distance: 900 },
  { id: 24, name: "Ski Resort Family Flat", location: "Kranjska Gora", price: 165, rating: 4.7, distance: 500 },
  { id: 25, name: "Mountain View Retreat", location: "Kranjska Gora", price: 175, rating: 4.8, distance: 700 },

  { id: 26, name: "Portorož Beach Apartment", location: "Portorož", price: 140, rating: 4.4, distance: 200 },
  { id: 27, name: "Portorož Family Suite", location: "Portorož", price: 160, rating: 4.6, distance: 300 },
  { id: 28, name: "Portorož Sea Balcony", location: "Portorož", price: 190, rating: 4.9, distance: 100 },
  { id: 29, name: "Luxury Spa Resort Flat", location: "Portorož", price: 220, rating: 5.0, distance: 150 },
  { id: 30, name: "Portorož Marina View", location: "Portorož", price: 145, rating: 4.3, distance: 350 },

  { id: 31, name: "Koper Old Town Apartment", location: "Koper", price: 95, rating: 4.2, distance: 300 },
  { id: 32, name: "Koper Sea View Studio", location: "Koper", price: 115, rating: 4.5, distance: 200 },
  { id: 33, name: "Koper Historic Center Flat", location: "Koper", price: 80, rating: 4.0, distance: 450 },
  { id: 34, name: "Koper Modern Apartment", location: "Koper", price: 105, rating: 4.3, distance: 350 },
  { id: 35, name: "Koper Marina Loft", location: "Koper", price: 125, rating: 4.4, distance: 250 },

  { id: 36, name: "Celje City Center Flat", location: "Celje", price: 70, rating: 3.9, distance: 600 },
  { id: 37, name: "Celje Modern Studio", location: "Celje", price: 85, rating: 4.2, distance: 800 },
  { id: 38, name: "Celje Castle View Loft", location: "Celje", price: 100, rating: 4.4, distance: 300 },
  { id: 39, name: "Celje Elegant Apartment", location: "Celje", price: 115, rating: 4.1, distance: 450 },
  { id: 40, name: "Celje Budget Room", location: "Celje", price: 55, rating: 3.8, distance: 900 },

  { id: 41, name: "Velenje Lake Apartment", location: "Velenje", price: 80, rating: 4.0, distance: 300 },
  { id: 42, name: "Velenje Town Center Flat", location: "Velenje", price: 65, rating: 3.9, distance: 450 },
  { id: 43, name: "Velenje Modern Suite", location: "Velenje", price: 95, rating: 4.3, distance: 500 },
  { id: 44, name: "Velenje Family Apartment", location: "Velenje", price: 110, rating: 4.5, distance: 650 },
  { id: 45, name: "Velenje Cozy Studio", location: "Velenje", price: 60, rating: 3.7, distance: 700 },

  { id: 46, name: "Novo Mesto Riverside Flat", location: "Novo Mesto", price: 75, rating: 4.0, distance: 300 },
  { id: 47, name: "Novo Mesto Center Apartment", location: "Novo Mesto", price: 85, rating: 4.2, distance: 400 },
  { id: 48, name: "NM Family Suite", location: "Novo Mesto", price: 110, rating: 4.5, distance: 500 },
  { id: 49, name: "NM Quiet Neighborhood Loft", location: "Novo Mesto", price: 90, rating: 4.1, distance: 350 },
  { id: 50, name: "NM River View Studio", location: "Novo Mesto", price: 95, rating: 4.3, distance: 280 },

  { id: 51, name: "Tržič Mountain Apartment", location: "Tržič", price: 65, rating: 3.9, distance: 1200 },
  { id: 52, name: "Tržič Alpine Retreat", location: "Tržič", price: 90, rating: 4.3, distance: 900 },
  { id: 53, name: "Tržič Cozy Cabin", location: "Tržič", price: 55, rating: 3.8, distance: 1400 },
  { id: 54, name: "Tržič Valley Suite", location: "Tržič", price: 115, rating: 4.6, distance: 700 },
  { id: 55, name: "Tržič Modern Flat", location: "Tržič", price: 85, rating: 4.2, distance: 800 },

  { id: 56, name: "Škofja Loka Medieval Loft", location: "Škofja Loka", price: 115, rating: 4.6, distance: 450 },
  { id: 57, name: "Škofja Loka Old Town Studio", location: "Škofja Loka", price: 90, rating: 4.2, distance: 350 },
  { id: 58, name: "Škofja Loka Cozy Flat", location: "Škofja Loka", price: 75, rating: 4.0, distance: 600 },
  { id: 59, name: "Škofja Loka Castle View", location: "Škofja Loka", price: 135, rating: 4.7, distance: 250 },
  { id: 60, name: "Škofja Loka Budget Room", location: "Škofja Loka", price: 55, rating: 3.6, distance: 800 },

  { id: 61, name: "Izola Sea Apartment", location: "Izola", price: 120, rating: 4.4, distance: 200 },
  { id: 62, name: "Izola Coastal Suite", location: "Izola", price: 145, rating: 4.7, distance: 150 },
  { id: 63, name: "Izola Old Town Flat", location: "Izola", price: 95, rating: 4.1, distance: 350 },
  { id: 64, name: "Izola Marina View Studio", location: "Izola", price: 110, rating: 4.3, distance: 300 },
  { id: 65, name: "Izola Beach Loft", location: "Izola", price: 135, rating: 4.6, distance: 100 },

  { id: 66, name: "Postojna Cave Apartment", location: "Postojna", price: 85, rating: 4.2, distance: 500 },
  { id: 67, name: "Postojna Center Loft", location: "Postojna", price: 75, rating: 3.9, distance: 800 },
  { id: 68, name: "Postojna Quiet Studio", location: "Postojna", price: 65, rating: 3.8, distance: 1200 },
  { id: 69, name: "Postojna Modern Flat", location: "Postojna", price: 95, rating: 4.3, distance: 600 },
  { id: 70, name: "Postojna Family Suite", location: "Postojna", price: 110, rating: 4.5, distance: 400 },

  { id: 71, name: "Hrastnik Green Valley Apartment", location: "Hrastnik", price: 60, rating: 3.7, distance: 900 },
  { id: 72, name: "Hrastnik Cozy Home", location: "Hrastnik", price: 55, rating: 3.8, distance: 700 },
  { id: 73, name: "Hrastnik Forest Retreat", location: "Hrastnik", price: 80, rating: 4.1, distance: 600 },
  { id: 74, name: "Hrastnik Family Loft", location: "Hrastnik", price: 95, rating: 4.2, distance: 750 },
  { id: 75, name: "Hrastnik Studio", location: "Hrastnik", price: 45, rating: 3.5, distance: 1300 },

  { id: 76, name: "Dravograd River Apartment", location: "Dravograd", price: 70, rating: 3.9, distance: 500 },
  { id: 77, name: "Dravograd Center Flat", location: "Dravograd", price: 65, rating: 3.7, distance: 700 },
  { id: 78, name: "Dravograd Mountain View", location: "Dravograd", price: 85, rating: 4.2, distance: 900 },
  { id: 79, name: "Dravograd Cozy Studio", location: "Dravograd", price: 55, rating: 3.6, distance: 800 },
  { id: 80, name: "Dravograd Peaceful Retreat", location: "Dravograd", price: 90, rating: 4.3, distance: 1000 },

  { id: 81, name: "Jesenice City Flat", location: "Jesenice", price: 65, rating: 3.8, distance: 400 },
  { id: 82, name: "Jesenice Mountain View", location: "Jesenice", price: 80, rating: 4.1, distance: 900 },
  { id: 83, name: "Jesenice Cozy Studio", location: "Jesenice", price: 55, rating: 3.6, distance: 600 },
  { id: 84, name: "Jesenice Central Apartment", location: "Jesenice", price: 75, rating: 3.9, distance: 500 },
  { id: 85, name: "Jesenice Family Suite", location: "Jesenice", price: 100, rating: 4.3, distance: 700 },

  { id: 86, name: "Žalec Green Studio", location: "Žalec", price: 70, rating: 3.7, distance: 850 },
  { id: 87, name: "Žalec Hops Valley Flat", location: "Žalec", price: 95, rating: 4.2, distance: 500 },
  { id: 88, name: "Žalec Cozy Apartment", location: "Žalec", price: 60, rating: 3.6, distance: 900 },
  { id: 89, name: "Žalec Modern Loft", location: "Žalec", price: 85, rating: 4.0, distance: 700 },
  { id: 90, name: "Žalec Budget Room", location: "Žalec", price: 50, rating: 3.5, distance: 1100 },

  { id: 91, name: "Murska Sobota Center Flat", location: "Murska Sobota", price: 65, rating: 3.8, distance: 500 },
  { id: 92, name: "Murska Sobota Modern Studio", location: "Murska Sobota", price: 85, rating: 4.1, distance: 700 },
  { id: 93, name: "Murska Sobota Family Suite", location: "Murska Sobota", price: 100, rating: 4.3, distance: 900 },
  { id: 94, name: "Murska Sobota Quiet Loft", location: "Murska Sobota", price: 75, rating: 4.0, distance: 600 },
  { id: 95, name: "Murska Sobota Budget Room", location: "Murska Sobota", price: 55, rating: 3.6, distance: 1000 },

  { id: 96, name: "Rogaška Slatina Spa Flat", location: "Rogaška Slatina", price: 140, rating: 4.6, distance: 300 },
  { id: 97, name: "Rogaška Wellness Studio", location: "Rogaška Slatina", price: 120, rating: 4.4, distance: 400 },
  { id: 98, name: "Rogaška Luxury Suite", location: "Rogaška Slatina", price: 180, rating: 4.9, distance: 200 },
  { id: 99, name: "Rogaška Park Apartment", location: "Rogaška Slatina", price: 95, rating: 4.1, distance: 600 },
  { id: 100, name: "Rogaška Elegant Loft", location: "Rogaška Slatina", price: 160, rating: 4.5, distance: 350 },
];
